### ISSUE TITLE
Some Issues that I came across while using streamnative cloud pulsar

### ISSUE THREAD

**Issue by HashZhang** [streamnative/pulsar#4084] opened 2022-04-19 06:51 UTC
I am very interested in adopting Pulsar with Pulsar SQL with my organization and I want to replace the RocketMQ and use StreamNative Cloud with AWS for a total managed deployment, but I came across some Issues:

1. I want to have a peek at the message consumed, but the amount here seems no effect.
![1650350453(1)](https://user-images.githubusercontent.com/15627489/163942201-8f2777dd-d9bb-4a81-8c2e-ebce21496dad.png)

2. I am very attracted to Pulsar SQL you have, which allows much imagination at SQL query messages and Online data analysis toward Pulsar. However I got some issues with  Pulsar SQL you provided based on flink:
![1650350956(1)](https://user-images.githubusercontent.com/15627489/163943016-6a99e2bb-821c-42fe-a25f-70f8a8a14660.png)

looking forward to your response

**Comment by sijie** [comment] 2022-04-19 07:08
@HashZhang 

For question 1, the peek command only peeks the messages in the backlog of a given subscription. Can you check the backlog size of your subscription?

For question 2, can you let us know the name of your organization & instance? We can take a look at it.

**Comment by HashZhang** [comment] 2022-04-19 08:34
> @HashZhang
> 
> For question 1, the peek command only peeks the messages in the backlog of a given subscription. Can you check the backlog size of your subscription?
> 
> For question 2, can you let us know the name of your organization & instance? We can take a look at it.

Thanks for your kind reply:

 - Q1: Got it, but as I am moving from rocketmq, therefore I may be confused why can't I peek at the messages already consumed, I suggest you provide a description on that~
 - Q2: Thanks a lot, I just remove the flink cluster and build a new one, this time it keeps stalling on this phase(for almost an hour till now):
 
![1650357121(1)](https://user-images.githubusercontent.com/15627489/163960282-507ca0c3-83fc-4c90-980b-6102484b470c.png)

By the way, my instance access point is: https://test-cluster-zhx1.o-rylby.snio.cloud

**Comment by tuteng** [comment] 2022-04-19 09:57
@HashZhang Can you try again, I think it's fixed now

**Comment by HashZhang** [comment] 2022-04-19 10:42
@tuteng 
Thanks, the flink cluster is settled, but the query still got internal server error:
![1650364910(1)](https://user-images.githubusercontent.com/15627489/163986939-c0e07fea-b908-4b25-a5c3-6228cbfddc4e.png)

**Comment by tuteng** [comment] 2022-04-21 06:42
After syncing with the user, I think this issue has been resolved, so we can consider closing this issue, the root cause of which is the incorrect type of timestamp setting

**Closed by tuteng** 2022-04-21 06:42 UTC
Labels: type/bug
